DATABASE_SECRET_KEY: 'randomkey'
DB_URI: mysql://fluxmonkey:@syahmed-appr-test-quayio-production-py3-20220619.cyx5kuwaeapz.us-east-1.rds.amazonaws.com:3306/quay
# If backend is run outside a container:
# DB_URI: postgresql://quay:quay@0.0.0.0:5432/quay
is_local: true
authentication:
  url: http://host.docker.internal:8081/auth
  realm: Test
  clientid: test-client-id
  role: admin-access
ENV: development
DEBUG: true
